### ISSUE TITLE
Diff syntax support

### ISSUE THREAD

**Issue by CodinCat** [siamak/panda-syntax-sublime#1]
Panda is one of my favorite color scheme, but it doesn't support Diff syntax for now.

Current diff view of panda, just highlight nothing:

![2016-09-05 12 22 32](https://cloud.githubusercontent.com/assets/3193344/18237402/767dab6a-7363-11e6-9714-f430a63994d1.png)

Hope there is something like this:

![2016-09-05 12 18 18](https://cloud.githubusercontent.com/assets/3193344/18237380/29fcbce0-7363-11e6-9b60-dc4287c9cb2d.png)

thanks.

**Comment by siamak** [comment]
@CodinCat When People loves Panda, I'm so happy :) What's your package for Diff ing files on Sublime Text?

**Comment by CodinCat** [comment]
Umm.. I'm using "Git" (the package name is just Git), but I think Sublime itself support Diff syntax?

Not sure, but you can just right click on a modified file and click  "Show Unsaved Changes..", the syntax of output screen is "Diff"

**Comment by siamak** [comment]
@CodinCat I'll check it 👍
