### ISSUE TITLE
Question : Material theme with Panda 

### ISSUE THREAD

**Issue by kossa** [siamak/panda-syntax-sublime#3]
Hello,

Really I love the syntax and I want to use it with Material I got this : 

![image](https://user-images.githubusercontent.com/1175584/30848688-c2c44c04-a297-11e7-87af-ac3a036473ac.png)

I want to keep the right color

**Comment by siamak** [comment]
@kossa I guess you can set a theme and a syntax theme for sublime text.

**Comment by kossa** [comment]
![image](https://user-images.githubusercontent.com/1175584/30861915-2019576a-a2c4-11e7-872c-04fd03c66f26.png)
